controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

hand_controller:
  ros__parameters:
    joints:
      - sabre_finger_1_rotatory_joint
      - sabre_finger_1_flexor_1_joint
      - sabre_finger_1_flexor_2_joint
      - sabre_finger_1_flexor_3_joint
      - sabre_finger_2_rotatory_joint
      - sabre_finger_2_flexor_1_joint
      - sabre_finger_2_flexor_2_joint
      - sabre_finger_2_flexor_3_joint
      - sabre_finger_3_rotatory_joint
      - sabre_finger_3_flexor_1_joint
      - sabre_finger_3_flexor_2_joint
      - sabre_finger_3_flexor_3_joint
      - sabre_thumb_rotatory_joint
      - sabre_thumb_flexor_1_joint
      - sabre_thumb_flexor_2_joint
      - sabre_thumb_flexor_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 1.0
